name: authenticator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.8.4
  google_fonts: ^4.0.3
  package_info_plus: ^3.0.3
  http: ^0.13.5
  get_storage: ^2.1.1
  intl: ^0.17.0
  connectivity_plus: ^3.0.3
  date_time_picker: ^2.1.0
  flutter_svg: ^2.0.7
  gradient_circular_progress_indicator: ^0.0.4
  flutter_switch: ^0.3.2
  font_awesome_flutter: ^10.5.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

